<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 8 Design and Sampling | Impact Evaluation in Practice</title>
  <meta name="description" content="Solutions for Impact Evaluation in Practice (2nd Edition)." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 8 Design and Sampling | Impact Evaluation in Practice" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Solutions for Impact Evaluation in Practice (2nd Edition)." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 8 Design and Sampling | Impact Evaluation in Practice" />
  
  <meta name="twitter:description" content="Solutions for Impact Evaluation in Practice (2nd Edition)." />
  

<meta name="author" content="Liam F. Beiser-McGrath" />
<meta name="author" content="Lecturer (Assistant Professor) in Politics, Royal Holloway, University of London" />
<meta name="author" content="www.liambeisermcgrath.com" />
<meta name="author" content="liam@liambeisermcgrath.com" />


<meta name="date" content="2020-07-29" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="matching.html"/>
<link rel="next" href="session-info.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Impact Evaluation in Practice Solutions</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preamble</a></li>
<li class="chapter" data-level="" data-path="about-the-author.html"><a href="about-the-author.html"><i class="fa fa-check"></i>About the Author</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#variable-definitions"><i class="fa fa-check"></i><b>1.1</b> Variable Definitions</a><ul>
<li class="chapter" data-level="1.1.1" data-path="intro.html"><a href="intro.html#outcome-variable"><i class="fa fa-check"></i><b>1.1.1</b> Outcome Variable</a></li>
<li class="chapter" data-level="1.1.2" data-path="intro.html"><a href="intro.html#control-variables"><i class="fa fa-check"></i><b>1.1.2</b> Control Variables</a></li>
<li class="chapter" data-level="1.1.3" data-path="intro.html"><a href="intro.html#other-variables"><i class="fa fa-check"></i><b>1.1.3</b> Other Variables</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="causal-inference-and-counterfactuals.html"><a href="causal-inference-and-counterfactuals.html"><i class="fa fa-check"></i><b>2</b> Causal Inference and Counterfactuals</a><ul>
<li class="chapter" data-level="2.1" data-path="causal-inference-and-counterfactuals.html"><a href="causal-inference-and-counterfactuals.html#before-after-designs"><i class="fa fa-check"></i><b>2.1</b> Before-After Designs</a></li>
<li class="chapter" data-level="2.2" data-path="causal-inference-and-counterfactuals.html"><a href="causal-inference-and-counterfactuals.html#enrolled-vs.-non-enrolled"><i class="fa fa-check"></i><b>2.2</b> Enrolled vs. Non-Enrolled</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="randomised-assignment.html"><a href="randomised-assignment.html"><i class="fa fa-check"></i><b>3</b> Randomised Assignment</a></li>
<li class="chapter" data-level="4" data-path="instrumental-variables.html"><a href="instrumental-variables.html"><i class="fa fa-check"></i><b>4</b> Instrumental Variables</a></li>
<li class="chapter" data-level="5" data-path="regression-discontinuity-designs.html"><a href="regression-discontinuity-designs.html"><i class="fa fa-check"></i><b>5</b> Regression Discontinuity Designs</a></li>
<li class="chapter" data-level="6" data-path="difference-in-differences.html"><a href="difference-in-differences.html"><i class="fa fa-check"></i><b>6</b> Difference-in-Differences</a></li>
<li class="chapter" data-level="7" data-path="matching.html"><a href="matching.html"><i class="fa fa-check"></i><b>7</b> Matching</a></li>
<li class="chapter" data-level="8" data-path="design-and-sampling.html"><a href="design-and-sampling.html"><i class="fa fa-check"></i><b>8</b> Design and Sampling</a><ul>
<li class="chapter" data-level="8.1" data-path="design-and-sampling.html"><a href="design-and-sampling.html#power-calculations-with-clusters"><i class="fa fa-check"></i><b>8.1</b> Power Calculations with Clusters</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="session-info.html"><a href="session-info.html"><i class="fa fa-check"></i><b>9</b> Session Info</a></li>
<li class="divider"></li>
<li><a href="www.liambeisermcgrath.com" target="blank">www.liambeisermcgrath.com</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Impact Evaluation in Practice</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="design-and-sampling" class="section level1">
<h1><span class="header-section-number">Chapter 8</span> Design and Sampling</h1>
<p>Let us say that the ministry of health was pleased with the quality and results of the evaluation of the Health Insurance Subsidy Program (HISP). However, before scaling up the pro- gram, the ministry decides to pilot an expanded version of the program, which they call HISP+. The original HISP pays for part of the cost of health insurance for poor rural households, covering costs of primary care and drugs, but it does not cover hospitalization. The minister of health wonders whether an expanded HISP+ that also covers hospitalization would further lower out-of-pocket health expenditures of poor households. The ministry asks you to design an impact evaluation to assess whether HISP+ would decrease health expenditures for poor rural households.</p>
<p>In this case, choosing an impact evaluation design is not a challenge for you: HISP+ has limited resources and cannot be implemented universally immediately. As a result, you have concluded that randomized assignment would be the most viable and robust impact evaluation method. The minister of health understands how well the randomized assignment method can work and is supportive.</p>
<p>To finalize the design of the impact evaluation, you have hired a statistician who will help you establish how big a sample is needed. Before they start working, the statistician asks you for some key inputs. They uses a checklist of five questions.</p>
<p><strong>1. Will the HISP+ program generate clusters?</strong> At this point, you are not totally sure. You believe that it might be possible to randomize the expanded benefit package at the household level among all poor rural households that already benefit from HISP. However, you are aware that the minister of health may prefer to assign the expanded program at the village level, and that would create clusters. The statistician sug- gests conducting power calculations for a benchmark case without clusters, and then considering how results would change with clusters.</p>
<p><strong>2. What is the outcome indicator?</strong> You explain that the government is interested in a well-defined indicator: out-of-pocket health expenditures of poor households. The statistician looks for the most up-to-date source to obtain benchmark values for this indicator and suggests using the follow-up survey from the HISP evaluation. They notes that among households that received HISP, the per capita yearly out-of-pocket health expenditures have averaged US$7.84.</p>
<p><strong>3. What is the minimum level of impact that would justify the investment in the intervention?</strong> In other words, what decrease in out-of-pocket health expenditures below the average of US$7.84 would make this intervention worthwhile? The statistician stresses that this is not only a technical consideration, but truly a policy question; that is why a policy maker like you must set the minimum effect that the evaluation should be able to detect. You remember that based on ex ante economic analysis, the HISP+ program would be considered effective if it reduced household out-of-pocket health expenditures by US$2. Still, you know that for the purpose of the evaluation, it may be better to be conservative in deter- mining the minimum detectable impact, since any smaller impact is unlikely to be captured. To understand how the required sample size varies based on the minimum detectable effect, you suggest that the statistician perform calculations for a minimum reduction of out-of-pocket health expenditures of US$1, US$2, and US$3.</p>
<p><strong>4. What is the variance of the outcome indicator in the population of interest?</strong> The statistician goes back to the data set of treated HISP households, pointing out that the standard deviation of out-of-pocket health expenditures is US$8.</p>
<p><strong>5. What would be a reasonable level of power for the evaluation being conducted?</strong> The statistician adds that power calculations are usually conducted for a power between 0.8 and 0.9. They recommends 0.9, but offers to perform robustness checks later for a less conservative level of 0.8.</p>
<p>We can calculate all the summary statistics we need as follows</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="design-and-sampling.html#cb40-1"></a><span class="co"># mean and standard deviation of outcome</span></span>
<span id="cb40-2"><a href="design-and-sampling.html#cb40-2"></a>sumstats &lt;-<span class="st"> </span>df_elig <span class="op">%&gt;%</span></span>
<span id="cb40-3"><a href="design-and-sampling.html#cb40-3"></a><span class="st">  </span><span class="kw">filter</span>(round <span class="op">==</span><span class="st"> </span><span class="dv">1</span> <span class="op">&amp;</span><span class="st"> </span>treatment_locality <span class="op">==</span><span class="st"> </span><span class="dv">1</span>) <span class="op">%&gt;%</span></span>
<span id="cb40-4"><a href="design-and-sampling.html#cb40-4"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean_health =</span> <span class="kw">mean</span>(health_expenditures),</span>
<span id="cb40-5"><a href="design-and-sampling.html#cb40-5"></a>            <span class="dt">sd_health =</span> <span class="kw">sd</span>(health_expenditures),</span>
<span id="cb40-6"><a href="design-and-sampling.html#cb40-6"></a>            <span class="dt">mean_hospital =</span> <span class="kw">mean</span>(hospital),</span>
<span id="cb40-7"><a href="design-and-sampling.html#cb40-7"></a>            <span class="dt">sd_hospital =</span> <span class="kw">sd</span>(hospital))</span></code></pre></div>
<p>Equipped with all this information, the statistician undertakes the
power calculations.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="design-and-sampling.html#cb41-1"></a>power_calc_health &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">d_health_expenditures =</span> <span class="kw">rep</span>(<span class="op">-</span><span class="dv">1</span><span class="op">:-</span><span class="dv">3</span>,<span class="dv">2</span>),</span>
<span id="cb41-2"><a href="design-and-sampling.html#cb41-2"></a>                            <span class="dt">power =</span> <span class="kw">rep</span>(<span class="kw">c</span>(<span class="fl">0.8</span>, <span class="fl">0.9</span>), <span class="dt">each =</span> <span class="dv">3</span>)) <span class="op">%&gt;%</span></span>
<span id="cb41-3"><a href="design-and-sampling.html#cb41-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">n_required =</span> <span class="kw">map2</span>(d_health_expenditures, power,</span>
<span id="cb41-4"><a href="design-and-sampling.html#cb41-4"></a>                           <span class="op">~</span><span class="st"> </span>{<span class="kw">pwr.t.test</span>(<span class="dt">d =</span> .x <span class="op">/</span><span class="st"> </span>sumstats<span class="op">$</span>sd_health,</span>
<span id="cb41-5"><a href="design-and-sampling.html#cb41-5"></a>                                         <span class="dt">sig.level =</span> <span class="fl">0.05</span>, <span class="dt">power =</span> .y)<span class="op">$</span>n}) <span class="op">%&gt;%</span></span>
<span id="cb41-6"><a href="design-and-sampling.html#cb41-6"></a><span class="st">           </span><span class="kw">unlist</span>() <span class="op">%&gt;%</span></span>
<span id="cb41-7"><a href="design-and-sampling.html#cb41-7"></a><span class="st">           </span><span class="kw">ceiling</span>())  </span></code></pre></div>
<p>As agreed, they first present the more conservative case of a power of 0.9.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="design-and-sampling.html#cb42-1"></a>power_calc_health <span class="op">%&gt;%</span></span>
<span id="cb42-2"><a href="design-and-sampling.html#cb42-2"></a><span class="st">  </span><span class="kw">filter</span>(power <span class="op">==</span><span class="st"> </span><span class="fl">0.9</span>) <span class="op">%&gt;%</span></span>
<span id="cb42-3"><a href="design-and-sampling.html#cb42-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">mde =</span> <span class="kw">gsub</span>(<span class="st">&quot;-&quot;</span>, <span class="st">&quot;$&quot;</span>, d_health_expenditures)) <span class="op">%&gt;%</span></span>
<span id="cb42-4"><a href="design-and-sampling.html#cb42-4"></a><span class="st">  </span><span class="kw">select</span>(mde, power, n_required) <span class="op">%&gt;%</span></span>
<span id="cb42-5"><a href="design-and-sampling.html#cb42-5"></a><span class="st">  </span><span class="kw">kable</span>(<span class="dt">align =</span> <span class="st">&quot;c&quot;</span>, </span>
<span id="cb42-6"><a href="design-and-sampling.html#cb42-6"></a>        <span class="dt">col.names =</span> <span class="kw">c</span>(<span class="st">&quot;Minimum Detectable Effect&quot;</span>, <span class="st">&quot;Power&quot;</span>, </span>
<span id="cb42-7"><a href="design-and-sampling.html#cb42-7"></a>                      <span class="st">&quot;Sample Required per Group&quot;</span>),</span>
<span id="cb42-8"><a href="design-and-sampling.html#cb42-8"></a>        <span class="dt">caption =</span> <span class="st">&quot;Evaluating HISP+: Sample Size Required to Detect Various Minimum Detectable Effects, Power = 0.9&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb42-9"><a href="design-and-sampling.html#cb42-9"></a><span class="st">  </span><span class="kw">kable_styling</span>(<span class="dt">full_width =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-28">Table 8.1: </span>Evaluating HISP+: Sample Size Required to Detect Various Minimum Detectable Effects, Power = 0.9
</caption>
<thead>
<tr>
<th style="text-align:center;">
Minimum Detectable Effect
</th>
<th style="text-align:center;">
Power
</th>
<th style="text-align:center;">
Sample Required per Group
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
$1
</td>
<td style="text-align:center;">
0.9
</td>
<td style="text-align:center;">
1345
</td>
</tr>
<tr>
<td style="text-align:center;">
$2
</td>
<td style="text-align:center;">
0.9
</td>
<td style="text-align:center;">
337
</td>
</tr>
<tr>
<td style="text-align:center;">
$3
</td>
<td style="text-align:center;">
0.9
</td>
<td style="text-align:center;">
151
</td>
</tr>
</tbody>
</table>
<p>The statistician concludes that to detect a US$2 decrease in out-of-pocket health expenditures with a power of 0.9, the sample needs to contain at least 672 units (336 treated units and 336 comparison units, with no clustering). They notes that if you were satisfied to detect a US$3 decrease in out-of-pocket health expenditures, a smaller sample of at least 300 units (150 units in each group) would be sufficient. By contrast, a much larger sample of at least 2,688 units (1,344 in each group) would be needed to detect a US$1 decrease in out-of-pocket health expenditures.</p>
<p>The statistician then produces another table for a power level of 0.8.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="design-and-sampling.html#cb43-1"></a>power_calc_health <span class="op">%&gt;%</span></span>
<span id="cb43-2"><a href="design-and-sampling.html#cb43-2"></a><span class="st">  </span><span class="kw">filter</span>(power <span class="op">==</span><span class="st"> </span><span class="fl">0.8</span>) <span class="op">%&gt;%</span></span>
<span id="cb43-3"><a href="design-and-sampling.html#cb43-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">mde =</span> <span class="kw">gsub</span>(<span class="st">&quot;-&quot;</span>, <span class="st">&quot;$&quot;</span>, d_health_expenditures)) <span class="op">%&gt;%</span></span>
<span id="cb43-4"><a href="design-and-sampling.html#cb43-4"></a><span class="st">  </span><span class="kw">select</span>(mde, power, n_required) <span class="op">%&gt;%</span></span>
<span id="cb43-5"><a href="design-and-sampling.html#cb43-5"></a><span class="st">  </span><span class="kw">kable</span>(<span class="dt">align =</span> <span class="st">&quot;c&quot;</span>, </span>
<span id="cb43-6"><a href="design-and-sampling.html#cb43-6"></a>        <span class="dt">col.names =</span> <span class="kw">c</span>(<span class="st">&quot;Minimum Detectable Effect&quot;</span>, <span class="st">&quot;Power&quot;</span>, </span>
<span id="cb43-7"><a href="design-and-sampling.html#cb43-7"></a>                      <span class="st">&quot;Sample Required per Group&quot;</span>),</span>
<span id="cb43-8"><a href="design-and-sampling.html#cb43-8"></a>        <span class="dt">caption =</span> <span class="st">&quot;Evaluating HISP+: Sample Size Required to Detect Various Minimum Detectable Effects, Power = 0.8&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb43-9"><a href="design-and-sampling.html#cb43-9"></a><span class="st">  </span><span class="kw">kable_styling</span>(<span class="dt">full_width =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-29">Table 8.2: </span>Evaluating HISP+: Sample Size Required to Detect Various Minimum Detectable Effects, Power = 0.8
</caption>
<thead>
<tr>
<th style="text-align:center;">
Minimum Detectable Effect
</th>
<th style="text-align:center;">
Power
</th>
<th style="text-align:center;">
Sample Required per Group
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
$1
</td>
<td style="text-align:center;">
0.8
</td>
<td style="text-align:center;">
1005
</td>
</tr>
<tr>
<td style="text-align:center;">
$2
</td>
<td style="text-align:center;">
0.8
</td>
<td style="text-align:center;">
252
</td>
</tr>
<tr>
<td style="text-align:center;">
$3
</td>
<td style="text-align:center;">
0.8
</td>
<td style="text-align:center;">
113
</td>
</tr>
</tbody>
</table>
<p>The table shows that the required sample sizes are smaller for a power of 0.8 than for a power of 0.9. To detect a US$2 reduction in household out-of-pocket health expenditures, a total sample of at least 502 units would be sufficient. To detect a US$3 reduction, at least 224 units are needed. However, to detect a US$1 reduction, at least 2,008 units would be needed in the sample. The statistician stresses that the following results are typical of power calculations:</p>
<ul>
<li>The higher (more conservative) the level of power, the larger the required sample size.</li>
<li>The smaller the impact to be detected, the larger the required sample size.</li>
</ul>
<p>The statistician asks whether you would like to conduct power calculations for other outcomes of interest. You suggest also considering the sample size required to detect whether HISP+ affects the hospitalization rate. In the sample of treated HISP villages, a household member visits the hospital in a given year in 5 percent of households; this provides a benchmark rate.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="design-and-sampling.html#cb44-1"></a>power_calc_hospital &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">d_hospital =</span> <span class="kw">rep</span>(<span class="kw">c</span>(<span class="op">-</span>.<span class="dv">01</span>,<span class="op">-</span>.<span class="dv">02</span>, <span class="fl">-.03</span>),<span class="dv">2</span>),</span>
<span id="cb44-2"><a href="design-and-sampling.html#cb44-2"></a>                              <span class="dt">power =</span> <span class="kw">rep</span>(<span class="kw">c</span>(<span class="fl">0.8</span>, <span class="fl">0.9</span>), <span class="dt">each =</span> <span class="dv">3</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb44-3"><a href="design-and-sampling.html#cb44-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">n_required =</span> <span class="kw">map2</span>(d_hospital, power,</span>
<span id="cb44-4"><a href="design-and-sampling.html#cb44-4"></a>                           <span class="op">~</span><span class="st"> </span>{<span class="kw">pwr.t.test</span>(<span class="dt">d =</span> .x <span class="op">/</span><span class="st"> </span>sumstats<span class="op">$</span>sd_hospital,</span>
<span id="cb44-5"><a href="design-and-sampling.html#cb44-5"></a>                                         <span class="dt">sig.level =</span> <span class="fl">0.05</span>, <span class="dt">power =</span> .y)<span class="op">$</span>n}) <span class="op">%&gt;%</span></span>
<span id="cb44-6"><a href="design-and-sampling.html#cb44-6"></a><span class="st">           </span><span class="kw">unlist</span>() <span class="op">%&gt;%</span></span>
<span id="cb44-7"><a href="design-and-sampling.html#cb44-7"></a><span class="st">           </span><span class="kw">ceiling</span> ()) </span></code></pre></div>
<p>The statistician produces a new table, which shows that relatively large samples would be needed to detect changes in the hospitalization rate of 1, 2, or 3 percentage points from the baseline rate of 5 percent.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="design-and-sampling.html#cb45-1"></a>power_calc_hospital <span class="op">%&gt;%</span></span>
<span id="cb45-2"><a href="design-and-sampling.html#cb45-2"></a><span class="st">  </span><span class="kw">filter</span>(power <span class="op">==</span><span class="st"> </span><span class="fl">0.8</span>) <span class="op">%&gt;%</span></span>
<span id="cb45-3"><a href="design-and-sampling.html#cb45-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">mde =</span> <span class="kw">gsub</span>(<span class="st">&quot;-&quot;</span>, <span class="st">&quot;&quot;</span>, d_hospital <span class="op">*</span><span class="st"> </span><span class="dv">100</span>)) <span class="op">%&gt;%</span></span>
<span id="cb45-4"><a href="design-and-sampling.html#cb45-4"></a><span class="st">  </span><span class="kw">select</span>(mde, power, n_required) <span class="op">%&gt;%</span></span>
<span id="cb45-5"><a href="design-and-sampling.html#cb45-5"></a><span class="st">  </span><span class="kw">kable</span>(<span class="dt">align =</span> <span class="st">&quot;c&quot;</span>, </span>
<span id="cb45-6"><a href="design-and-sampling.html#cb45-6"></a>        <span class="dt">col.names =</span> <span class="kw">c</span>(<span class="st">&quot;Minimum Detectable Effect (%)&quot;</span>, <span class="st">&quot;Power&quot;</span>, </span>
<span id="cb45-7"><a href="design-and-sampling.html#cb45-7"></a>                      <span class="st">&quot;Sample Required per Group&quot;</span>),</span>
<span id="cb45-8"><a href="design-and-sampling.html#cb45-8"></a>        <span class="dt">caption =</span> <span class="st">&quot;Evaluating HISP+: Sample Size Required to Detect Various Minimum Desired Effects (Increase in Hospitalization Rate)&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb45-9"><a href="design-and-sampling.html#cb45-9"></a><span class="st">  </span><span class="kw">kable_styling</span>(<span class="dt">full_width =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:unnamed-chunk-31">Table 8.3: </span>Evaluating HISP+: Sample Size Required to Detect Various Minimum Desired Effects (Increase in Hospitalization Rate)
</caption>
<thead>
<tr>
<th style="text-align:center;">
Minimum Detectable Effect (%)
</th>
<th style="text-align:center;">
Power
</th>
<th style="text-align:center;">
Sample Required per Group
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
1
</td>
<td style="text-align:center;">
0.8
</td>
<td style="text-align:center;">
7257
</td>
</tr>
<tr>
<td style="text-align:center;">
2
</td>
<td style="text-align:center;">
0.8
</td>
<td style="text-align:center;">
1815
</td>
</tr>
<tr>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
0.8
</td>
<td style="text-align:center;">
808
</td>
</tr>
</tbody>
</table>
<p>The table shows that sample size requirements are larger for this outcome (the hospitalization rate) than for out-of-pocket health expenditures. The statistician concludes that if you are interested in detecting impacts on both outcomes, you should use the larger sample sizes implied by the power calculations performed on the hospitalization rates. If sample sizes from the power calculations performed for out-of-pocket health expenditures are used, the statistician suggests letting the minister of health know that the evaluation will not have sufficient power to detect policy-relevant effects on hospitalization rates.</p>
<p><strong>Which sample size would you recommend to estimate the impact of HISP+ on out-of-pocket health expenditures?</strong></p>
<p>This answer will depend on policy priorities and available budgets. Under randomized assignment at the individual level, a total sample size of 2,688 units (1,344 in each group) would be needed to detect a $1 decrease in out-of-pocket health expenditures with a power of 0.9. A total sample size of 672 (336 treated and 336 comparison units) would detect a change as small as $2 in health expenditures at the 0.9 power. This would cut the required sample and related data collection costs substantially. At the same time, it would still allow detecting the impacts that would make the program effective based on the ex-ante economic analysis. As such, such a sample may be a good compromise if budgets are limited.</p>
<p><strong>Would that sample size be sufficient to detect changes in the hospitalization rate?</strong></p>
<p>A sample size of 672 would not be sufficient to detect even a 3 percent change in hospitalization rate with a power of 0.9. Much larger sample sizes (above 1,614) will be required to detect impacts on hospitalization rates.</p>
<div id="power-calculations-with-clusters" class="section level2">
<h2><span class="header-section-number">8.1</span> Power Calculations with Clusters</h2>
<p>After your first discussion with the statistician about power calculations for HISP+, you decided to talk briefly to the minister of health about the implications of randomly assigning the expanded HISP+ benefits among all individuals in the population who receive the basic HISP plan. The consultation revealed that such a procedure would not be politically feasible: in that context, it would be hard to explain why one person would receive the expanded benefits, while her neighbor would not.</p>
<p>Instead of randomization at the individual level, you therefore suggest randomly selecting a number of HISP villages to pilot HISP+. All villagers in the selected village would then become eligible. This procedure will create clusters and thus require new power calculations. You now want to determine how large a sample is required to evaluate the impact of HISP+ when it is randomly assigned by cluster.</p>
<p>You consult with your statistician again. They reassures you: only a little more work is needed. On their checklist, only one question is left unanswered. They needs to know how variable the outcome indicator is within clusters. Luckily, this is also a question they can answer using the HISP data. They finds that the within-village correlation of out-of-pocket health expenditures is equal to 0.04.</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="design-and-sampling.html#cb46-1"></a><span class="co"># intraclass correlation, for cluster calculations</span></span>
<span id="cb46-2"><a href="design-and-sampling.html#cb46-2"></a>df_elig_t1r1 &lt;-<span class="st"> </span>df_elig <span class="op">%&gt;%</span></span>
<span id="cb46-3"><a href="design-and-sampling.html#cb46-3"></a><span class="st">  </span><span class="kw">filter</span>(round <span class="op">==</span><span class="st"> </span><span class="dv">1</span> <span class="op">&amp;</span><span class="st"> </span>treatment_locality <span class="op">==</span><span class="st"> </span><span class="dv">1</span>) <span class="op">%&gt;%</span></span>
<span id="cb46-4"><a href="design-and-sampling.html#cb46-4"></a><span class="st">  </span><span class="kw">select</span>(health_expenditures, locality_identifier)</span>
<span id="cb46-5"><a href="design-and-sampling.html#cb46-5"></a></span>
<span id="cb46-6"><a href="design-and-sampling.html#cb46-6"></a>icc_est &lt;-<span class="st"> </span><span class="kw">clus.rho</span>(df_elig_t1r1<span class="op">$</span>health_expenditures, </span>
<span id="cb46-7"><a href="design-and-sampling.html#cb46-7"></a>                df_elig_t1r1<span class="op">$</span>locality_identifier, </span>
<span id="cb46-8"><a href="design-and-sampling.html#cb46-8"></a>                <span class="dt">type =</span> <span class="dv">3</span>)<span class="op">$</span>icc</span>
<span id="cb46-9"><a href="design-and-sampling.html#cb46-9"></a>icc_est</span></code></pre></div>
<pre><code>##                value
## ANOVA rho 0.04061629</code></pre>
<p>They also ask whether an upper limit has been placed on the number of villages in which it would be feasible to implement the new pilot. Since the program now has 100 HISP villages, you explain that you could have, at most, 50 treatment villages and 50 comparison villages for HISP+. With that information, the statistician produces the power calculations shown in for a power of 0.8.</p>
<!-- ```{r} -->
<!-- crtpwr.2mean(alpha = 0.05, power = 0.8, m = 50, cv = 0, icc = icc_est,  -->
<!--              d = 2, varw = sumstats$sd_health^2, -->
<!--              n = NA) -->
<!-- ``` -->
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="design-and-sampling.html#cb48-1"></a><span class="co"># calculating all at once</span></span>
<span id="cb48-2"><a href="design-and-sampling.html#cb48-2"></a>power_clstr_calc_health &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">d_health_expenditures =</span> <span class="dv">-1</span><span class="op">:-</span><span class="dv">3</span>) <span class="op">%&gt;%</span></span>
<span id="cb48-3"><a href="design-and-sampling.html#cb48-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">n_required =</span> <span class="kw">map</span>(d_health_expenditures,</span>
<span id="cb48-4"><a href="design-and-sampling.html#cb48-4"></a>                           <span class="op">~</span><span class="st"> </span>{<span class="kw">crtpwr.2mean</span>(<span class="dt">d =</span> .x, <span class="dt">m =</span> <span class="dv">50</span>,</span>
<span id="cb48-5"><a href="design-and-sampling.html#cb48-5"></a>                                           <span class="dt">alpha =</span> <span class="fl">0.05</span>, <span class="dt">power =</span> <span class="fl">0.8</span>,</span>
<span id="cb48-6"><a href="design-and-sampling.html#cb48-6"></a>                                           <span class="dt">cv =</span> <span class="dv">0</span>, <span class="dt">icc =</span> icc_est,</span>
<span id="cb48-7"><a href="design-and-sampling.html#cb48-7"></a>                                           <span class="dt">varw =</span> sumstats<span class="op">$</span>sd_health<span class="op">^</span><span class="dv">2</span>)}) <span class="op">%&gt;%</span></span>
<span id="cb48-8"><a href="design-and-sampling.html#cb48-8"></a><span class="st">           </span><span class="kw">unlist</span>() <span class="op">%&gt;%</span></span>
<span id="cb48-9"><a href="design-and-sampling.html#cb48-9"></a><span class="st">           </span><span class="kw">ceiling</span>()) </span></code></pre></div>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="design-and-sampling.html#cb49-1"></a>power_clstr_calc_health <span class="op">%&gt;%</span></span>
<span id="cb49-2"><a href="design-and-sampling.html#cb49-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">mde =</span> <span class="kw">gsub</span>(<span class="st">&quot;-&quot;</span>, <span class="st">&quot;$&quot;</span>, d_health_expenditures),</span>
<span id="cb49-3"><a href="design-and-sampling.html#cb49-3"></a>         <span class="dt">total_clusters =</span> <span class="dv">50</span> <span class="op">*</span><span class="st"> </span><span class="dv">2</span>,</span>
<span id="cb49-4"><a href="design-and-sampling.html#cb49-4"></a>         <span class="dt">total_sample =</span> total_clusters <span class="op">*</span><span class="st"> </span>n_required) <span class="op">%&gt;%</span></span>
<span id="cb49-5"><a href="design-and-sampling.html#cb49-5"></a><span class="st">  </span><span class="kw">select</span>(mde, total_clusters, n_required, total_sample) <span class="op">%&gt;%</span></span>
<span id="cb49-6"><a href="design-and-sampling.html#cb49-6"></a><span class="st">  </span><span class="kw">kable</span>(<span class="dt">col.names =</span> <span class="kw">c</span>(<span class="st">&quot;Minimum Detectable Effect&quot;</span>, <span class="st">&quot;Number of Clusters&quot;</span>, </span>
<span id="cb49-7"><a href="design-and-sampling.html#cb49-7"></a>                      <span class="st">&quot;Units per Cluster&quot;</span>, <span class="st">&quot;Total Observations&quot;</span>),</span>
<span id="cb49-8"><a href="design-and-sampling.html#cb49-8"></a>        <span class="dt">align =</span> <span class="st">&quot;c&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb49-9"><a href="design-and-sampling.html#cb49-9"></a><span class="st">  </span><span class="kw">kable_styling</span>(<span class="dt">full_width =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Minimum Detectable Effect
</th>
<th style="text-align:center;">
Number of Clusters
</th>
<th style="text-align:center;">
Units per Cluster
</th>
<th style="text-align:center;">
Total Observations
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
$1
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
117
</td>
<td style="text-align:center;">
11700
</td>
</tr>
<tr>
<td style="text-align:center;">
$2
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
7
</td>
<td style="text-align:center;">
700
</td>
</tr>
<tr>
<td style="text-align:center;">
$3
</td>
<td style="text-align:center;">
100
</td>
<td style="text-align:center;">
3
</td>
<td style="text-align:center;">
300
</td>
</tr>
</tbody>
</table>
<p>The statistician concludes that to detect a US$2 decrease in out-of-pocket health expenditures, the sample must include at least 700 units: that is, 7 units per cluster in 100 clusters (50 clusters in the treatment group and 50 clusters in the comparison group). They note that this number is higher than in the sample under randomized assignment at the household level, which required only a total of 504 units (252 in the treatment group and 252 in the comparison group). To detect a US$3 decrease in out-of-pocket health expenditures, the sample would need to include at least 300 units, or 3 units in each of 100 clusters (50 clusters in the treatment group and 50 clusters in the comparison group).</p>
<p>The statistician then shows you how the total number of observations required in the sample varies with the total number of clusters. He decides to repeat the calculations for a minimum detectable effect of US$2 and a power of 0.8. The size of the total sample required to estimate such an effect increases strongly when the number of clusters diminishes. With 120 clusters, a sample of 600 observations would be needed. If only 30 clusters were available, the total sample would need to contain 1,920 observations. By contrast, if 90 clusters were available, only 720 observations would be needed.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="design-and-sampling.html#cb50-1"></a><span class="co"># calculating all at once</span></span>
<span id="cb50-2"><a href="design-and-sampling.html#cb50-2"></a>power_clstr_n_calc_health &lt;-<span class="st"> </span><span class="kw">tibble</span>(<span class="dt">n_clusters =</span> <span class="kw">c</span>(<span class="dv">15</span>, <span class="dv">29</span>, <span class="fl">40.5</span>, <span class="dv">45</span>, <span class="dv">60</span>)) <span class="op">%&gt;%</span></span>
<span id="cb50-3"><a href="design-and-sampling.html#cb50-3"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">n_required =</span> <span class="kw">map</span>(n_clusters,</span>
<span id="cb50-4"><a href="design-and-sampling.html#cb50-4"></a>                           <span class="op">~</span><span class="st"> </span>{<span class="kw">crtpwr.2mean</span>(<span class="dt">m =</span> .x, <span class="dt">d =</span> <span class="dv">2</span>,</span>
<span id="cb50-5"><a href="design-and-sampling.html#cb50-5"></a>                                           <span class="dt">alpha =</span> <span class="fl">0.05</span>, <span class="dt">power =</span> <span class="fl">0.8</span>,</span>
<span id="cb50-6"><a href="design-and-sampling.html#cb50-6"></a>                                           <span class="dt">cv =</span> <span class="dv">0</span>, <span class="dt">icc =</span> icc_est,</span>
<span id="cb50-7"><a href="design-and-sampling.html#cb50-7"></a>                                           <span class="dt">varw =</span> sumstats<span class="op">$</span>sd_health<span class="op">^</span><span class="dv">2</span>)}) <span class="op">%&gt;%</span></span>
<span id="cb50-8"><a href="design-and-sampling.html#cb50-8"></a><span class="st">           </span><span class="kw">unlist</span>() <span class="op">%&gt;%</span></span>
<span id="cb50-9"><a href="design-and-sampling.html#cb50-9"></a><span class="st">           </span><span class="kw">ceiling</span>())</span></code></pre></div>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="design-and-sampling.html#cb51-1"></a>power_clstr_n_calc_health <span class="op">%&gt;%</span></span>
<span id="cb51-2"><a href="design-and-sampling.html#cb51-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">mde =</span> <span class="st">&quot;$2&quot;</span>,</span>
<span id="cb51-3"><a href="design-and-sampling.html#cb51-3"></a>         <span class="co"># multiply clusters by 2, as power calculator works with number of</span></span>
<span id="cb51-4"><a href="design-and-sampling.html#cb51-4"></a>         <span class="co"># clusters per group (not total number of clusters)</span></span>
<span id="cb51-5"><a href="design-and-sampling.html#cb51-5"></a>         <span class="dt">total_clusters =</span> <span class="dv">2</span> <span class="op">*</span><span class="st"> </span>n_clusters, </span>
<span id="cb51-6"><a href="design-and-sampling.html#cb51-6"></a>         <span class="dt">total_sample =</span> total_clusters <span class="op">*</span><span class="st"> </span>n_required) <span class="op">%&gt;%</span></span>
<span id="cb51-7"><a href="design-and-sampling.html#cb51-7"></a><span class="st">  </span><span class="kw">select</span>(mde, total_clusters, n_required, total_sample) <span class="op">%&gt;%</span></span>
<span id="cb51-8"><a href="design-and-sampling.html#cb51-8"></a><span class="st">  </span><span class="kw">kable</span>(<span class="dt">col.names =</span> <span class="kw">c</span>(<span class="st">&quot;Minimum Detectable Effect&quot;</span>, <span class="st">&quot;Number of Clusters&quot;</span>, </span>
<span id="cb51-9"><a href="design-and-sampling.html#cb51-9"></a>                      <span class="st">&quot;Units per Cluster&quot;</span>, <span class="st">&quot;Total Observations&quot;</span>),</span>
<span id="cb51-10"><a href="design-and-sampling.html#cb51-10"></a>        <span class="dt">align =</span> <span class="st">&quot;c&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb51-11"><a href="design-and-sampling.html#cb51-11"></a><span class="st">  </span><span class="kw">kable_styling</span>(<span class="dt">full_width =</span> <span class="ot">TRUE</span>)</span></code></pre></div>
<table class="table" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:center;">
Minimum Detectable Effect
</th>
<th style="text-align:center;">
Number of Clusters
</th>
<th style="text-align:center;">
Units per Cluster
</th>
<th style="text-align:center;">
Total Observations
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center;">
$2
</td>
<td style="text-align:center;">
30
</td>
<td style="text-align:center;">
64
</td>
<td style="text-align:center;">
1920
</td>
</tr>
<tr>
<td style="text-align:center;">
$2
</td>
<td style="text-align:center;">
58
</td>
<td style="text-align:center;">
14
</td>
<td style="text-align:center;">
812
</td>
</tr>
<tr>
<td style="text-align:center;">
$2
</td>
<td style="text-align:center;">
81
</td>
<td style="text-align:center;">
9
</td>
<td style="text-align:center;">
729
</td>
</tr>
<tr>
<td style="text-align:center;">
$2
</td>
<td style="text-align:center;">
90
</td>
<td style="text-align:center;">
8
</td>
<td style="text-align:center;">
720
</td>
</tr>
<tr>
<td style="text-align:center;">
$2
</td>
<td style="text-align:center;">
120
</td>
<td style="text-align:center;">
5
</td>
<td style="text-align:center;">
600
</td>
</tr>
</tbody>
</table>
<p><strong>Which total sample size would you recommend to estimate the impact of HISP+ on out-of-pocket health expenditures?</strong></p>
<p>This answer will depend on policy priorities and available budgets. A total sample size of 600 households (with 120 villages and 5 households per village) would be appropriate for the evaluation, as this sample size would detect a change of $2 with a power of 0.8.</p>
<p><strong>In how many villages would you advise the minister of health to roll out HISP+?</strong></p>
<p>Power is maximized when the number of treatment and control observations is the same. If a total sample of 90 villages is needed, rolling out HISP+ to 45 villages would maximize power. The other 45 villages would be comparison villages.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="matching.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="session-info.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["iep_solutions.pdf", "iep_solutions.epub"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

</body>

</html>
